name: productivity_tracker_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  carousel_slider: ^4.2.1
  percent_indicator: ^4.2.3
  dropdown_button2: ^2.3.9
  pinput: ^3.0.1
  google_fonts: ^6.1.0
  sp_util: ^2.0.3
  email_auth: ^1.1.1
  flutter_easyloading: ^3.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icons/
